services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    # volumes:
      # - wordpress_data:/var/www/html
    restart: always # sure ?
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: . # verifier le contexte https://stackoverflow.com/questions/32997269/copying-a-file-in-a-dockerfile-no-such-file-or-directory
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    # legal ?
    # environment: 
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: enzo
    #   MYSQL_PASSWORD: enzo
    # volumes:
    #   - mariadb_data:/var/lib/mysql
      


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/mariadb
      o: bind