services:
  # mandatory
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - website_data:/var/www/home
    restart: always
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception
    restart: always
  website:
    container_name: website
    image: website
    build:
      context: .
      dockerfile: requirements/bonus/website/Dockerfile
    volumes:
      - website_data:/var/www/home
  # bonus
  redis:
    container_name: redis
    image: redis
    build:
      context: .
      dockerfile: requirements/bonus/redis/Dockerfile
    ports:
      - "6379:6379"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  dnsmasq:
    container_name: dnsmasq
    image: dnsmasq
    build:
      context: .
      dockerfile: requirements/bonus/dnsmasq/Dockerfile
    ports:
      - "53:53"
      - "53:53/udp"
    restart: always
    networks:
      - inception
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd/.
    image: vsftpd
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "50000-50005:50000-50005"
    networks:
      - inception
    restart: always

volumes:
  # mandatory
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/mariadb
      o: bind
  # bonus
  website_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/website
      o: bind

networks:
  inception:
    name: inception
    driver: bridge