services:
  dnsmasq:
    container_name: dnsmasq
    image: dnsmasq
    build:
      context: .
      dockerfile: requirements/bonus/dnsmasq/Dockerfile
    ports:
      - "53:53"
      - "53:53/udp"
    restart: always
    networks:
      - inception
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: . # verifier le contexte https://stackoverflow.com/questions/32997269/copying-a-file-in-a-dockerfile-no-such-file-or-directory
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    networks:
      - inception


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/enzo/data/mariadb
      o: bind


networks:
  inception:
    name: inception
    driver: bridge